FROM python:3.13-slim-bookworm@sha256:00faa2debb87529f9f0764e9491d8ba400a3678976616c3bd7cb193745ac20d1

RUN mkdir -p /etc /usr/local/bin \
    && printf '%s\n' 'verifier:x:2000:2000:RoleBench verifier:/:/bin/sh' >> /etc/passwd \
    && printf '%s\n' 'verifier:x:2000:' >> /etc/group
COPY verifier.py /usr/local/bin/rolebench-verifier
RUN chmod 0555 /usr/local/bin/rolebench-verifier

USER 2000:2000
WORKDIR /
CMD ["/usr/local/bin/rolebench-verifier"]
